[project]
name = "nonebot-plugin-parser"
version = "2.6.5"
description = "NoneBot2 链接分享解析 Alconna 版, 支持B站|抖音(含直播/图集/实况图)|快手|微博|小红书|YouTube|TikTok|Twitter|AcFun|NGA|pixiv|Instagram|BOOTH|GoodSmile|HeyBox"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ "name" = "ankoconmf", "email" = "jiawei.1108@qq.com" }]
keywords = [
  "acfun",
  "bilibili",
  "booth",
  "douyin",
  "goodsmile",
  "heybox",
  "instagram",
  "kuaishou",
  "nga",
  "nonebot",
  "nonebot2",
  "pixiv",
  "tiktok",
  "twitter",
  "video",
  "weibo",
  "xiaohongshu",
  "youtube",
]

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Framework :: AsyncIO",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Communications :: Chat",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Multimedia :: Video",
]

dependencies = [
  "rich>=13.0.0",
  "pillow>=11.0.0",
  "aiofiles>=25.1.0",
  "httpx>=0.27.2,<1.0.0",
  "msgspec>=0.20.0,<1.0.0",
  "nonebot2>=2.5.0,<3.0.0",
  "apilmoji[rich]>=0.3.1,<1.0.0",
  "beautifulsoup4>=4.12.0,<5.0.0",
  "curl_cffi>=0.13.0,<1.0.0,!=0.14.0",
  "bilibili-api-python>=17.4.2,<18.0.0",
  "nonebot-plugin-uninfo>=0.10.1,<1.0.0",
  "nonebot-plugin-alconna>=0.60.4,<1.0.0",
  "nonebot-plugin-localstore>=0.7.4,<1.0.0",
  "nonebot-plugin-apscheduler>=0.5.0,<1.0.0",
  "nonebot-plugin-htmlrender>=0.6.7",
  "emoji>=2.0.0",
  "psutil>=5.9.0",
  "DrissionPage>=4.0.0",
]

[project.urls]
IssueTracker = "https://github.com/ankoconmf/nonebot-plugin-parser-suan/issues"
Release = "https://github.com/ankoconmf/nonebot-plugin-parser-suan/releases"
Repository = "https://github.com/ankoconmf/nonebot-plugin-parser-suan"

[project.optional-dependencies]
ytdlp = ["yt-dlp[default]>=2025.2.21"]
emosvg = ["emosvg>=0.1.7"]
all = [
  "yt-dlp[default]>=2025.2.21",
  "emosvg>=0.1.7",
]

[build-system]
requires = ["uv_build>=0.11.0,<0.12.0"]
build-backend = "uv_build"

[tool.nonebot]
adapters = [
  { "name" = "Onebot V11", module_name = "nonebot.adapters.onebot.v11" },
]
plugins = ["nonebot_plugin_parser"]

[tool.ruff]
line-length = 120

[tool.ruff.format]
line-ending = "lf"

[tool.ruff.lint]
select = [
  "F",     # Pyflakes
  "W",     # pycodestyle warnings
  "E",     # pycodestyle errors
  "I",     # isort
  "UP",    # pyupgrade
  "Q",     # flake8-quotes
  "PYI",   # flake8-pyi
  "T10",   # flake8-debugger
  "T20",   # flake8-print
  "C4",    # flake8-comprehensions
  "RUF",   # Ruff-specific rules
]
ignore = [
  "E402",     # module-import-not-at-top-of-file
  "UP037",    # quoted-annotation
  "RUF001",   # ambiguous-unicode-character-string
  "RUF002",   # ambiguous-unicode-character-docstring
  "RUF003",   # ambiguous-unicode-character-comment
  "W191",     # indentation contains tabs
  "TID252",   # relative-import
]

[tool.ruff.lint.isort]
length-sort = true
known-first-party = ["nonebot_plugin_parser"]
extra-standard-library = ["typing_extensions"]
